apiVersion: v1
kind: Service
metadata:
  name: petclinic
  labels:
    run: petclinic
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    run: petclinic
