apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
spec:
  selector:
    matchLabels:
      run: petclinic
  replicas: 1
  template:
    metadata:
      labels:
        run: petclinic
    spec:
      volumes:
      - name: appinternals
        hostPath:
          path: "/opt/Panorama"
      containers:
      - name: petclinic
        image: docker.io/sionsmith/spring-petclinic
        ports:
        - containerPort: 8080
        env:
        - name: LD_PRELOAD
          value: "/opt/Panorama/hedzup/mn/lib64/librpil.so"
        volumeMounts:
        - name: appinternals
          mountPath: "/opt/Panorama"

