kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-jpet-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/jpetstore-mysql"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-jpet-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
