apiVersion: v1
kind: Service
metadata:
  name: jpetstore-svc
  labels:
    app: jpetstore-app
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: jpetstore-app
